In [87]:
import pandas as pd

In [88]:
# csv 폴더 안에 tran_1.csv, tran_2.csv 파일을 로드
tran_1 = pd.read_csv('../csv/tran_1.csv')
tran_2 = pd.read_csv('../csv/tran_2.csv')

In [89]:
tran_1.head(1)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502

In [90]:
tran_2.head(1)

  transaction_id   price         payment_date customer_id
0    T0000005113  295000  2019-06-15 07:20:27    TS169261

In [91]:
tran_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  5000 non-null   object
 1   price           5000 non-null   int64
 2   payment_date    5000 non-null   object
 3   customer_id     5000 non-null   object
dtypes: int64(1), object(3)
memory usage: 156.4+ KB

In [92]:
tran_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1786 entries, 0 to 1785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  1786 non-null   object
 1   price           1786 non-null   int64
 2   payment_date    1786 non-null   object
 3   customer_id     1786 non-null   object
dtypes: int64(1), object(3)
memory usage: 55.9+ KB

In [93]:
# tran_1, tran_2 데이터를 결합
    # 두 개의 데이터프레임은 테이블의 구조가 같은 형태
    # 단순한 행 결합
    # 두 개의 데이터프레임이 행 결합을 하면 rows의 개수는? -> 5000 + 1786 = 6786
# concat() 함수 이용
# pandas 안에 concat 함수 호출 --> 원본의 데이터라는 개념이 존재 x ->
# 결과를 저장하려면 새로운 변수에 대입
tran = pd.concat(
    [ tran_1, tran_2 ],axis = 0,ignore_index = True
)

In [94]:
tran.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6786 entries, 0 to 6785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6786 non-null   object
 1   price           6786 non-null   int64
 2   payment_date    6786 non-null   object
 3   customer_id     6786 non-null   object
dtypes: int64(1), object(3)
memory usage: 212.2+ KB

In [95]:
# tran_d_1.csv, tran_d_2.csv 파일을 로드
tran_d_1 = pd.read_csv('../csv/tran_d_1.csv')
tran_d_2 = pd.read_csv('../csv/tran_d_2.csv')

In [96]:
tran_d_1.head(1)

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1

In [97]:
tran_d_2.head(1)

   detail_id transaction_id item_id  quantity
0       5000    T0000004870    S002         3

In [98]:
tran_d_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       5000 non-null   int64
 1   transaction_id  5000 non-null   object
 2   item_id         5000 non-null   object
 3   quantity        5000 non-null   int64
dtypes: int64(2), object(2)
memory usage: 156.4+ KB

In [99]:
tran_d_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       2144 non-null   int64
 1   transaction_id  2144 non-null   object
 2   item_id         2144 non-null   object
 3   quantity        2144 non-null   int64
dtypes: int64(2), object(2)
memory usage: 67.1+ KB

In [100]:
# tran_d_1, tran_d_2 데이터프레임을 단순 행 결합
tran_d = pd.concat(
    [tran_d_1,tran_d_2],axis=0,ignore_index=True
)

In [101]:
tran_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       7144 non-null   int64
 1   transaction_id  7144 non-null   object
 2   item_id         7144 non-null   object
 3   quantity        7144 non-null   int64
dtypes: int64(2), object(2)
memory usage: 223.4+ KB

In [102]:
tran.head(1)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502

In [103]:
tran_d.head(1)

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1

In [104]:
tran_d['transaction_id'].value_counts()

transaction_id
T0000000790    4
T0000005598    3
T0000000231    3
T0000000547    3
T0000000683    3
              ..
T0000002420    1
T0000002419    1
T0000002418    1
T0000002417    1
T0000006898    1
Name: count, Length: 6786, dtype: int64

In [105]:
tran['transaction_id'].describe()

count            6786
unique           6786
top       T0000000113
freq                1
Name: transaction_id, dtype: object

In [106]:
# tran과 tran_d 데이터프레임을 결합
# 테이블의 구조는 다르게 구성 -> 단순한 행결합 불가능
# 인덱스의 개수가 다르다 -> 6786 // 7144개의 데이터
# 두개의 데이터프레임이 공통적으로 가지고 있는 데이터 컬럼은 존재하는가?
    # transaction_id 컬럼은 공통적으로 가지고 있다 -> 조인 결합이 가능
# tran의 인덱스의 수는 6786개
# tran_d의 인덱스의 수는 7144개
    # 두 개의 데이터프레임을 조인 결합 했을 때 -> 인덱스의 수는 어떻게 나올것인가?
    # 6786 // 7144 -> how에 따라 다르게 나올것인가?
transaction = pd.merge(
    tran,tran_d,
    # 조건 ( 두 개의 데이터프레임이 공통적으로 가지고 있는 컬럼의 이름 )
    on = 'transaction_id',
    # 결합의 방식은 어떻게 할것인가?
    how = 'outer'
)

In [107]:
# 총 4개의 데이터 파일을 하나의 데이터프레임으로 결합
transaction

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1
1,T0000000114,50000,2019-02-01 01:37:23,HD678019,1,S001,1
2,T0000000115,120000,2019-02-01 02:34:19,HD298120,2,S003,1
3,T0000000116,210000,2019-02-01 02:47:23,IK452215,3,S005,1
4,T0000000117,170000,2019-02-01 04:33:46,PL542865,4,S002,2
...,...,...,...,...,...,...,...
7139,T0000006894,180000,2019-07-31 21:20:44,HI400734,7139,S004,1
7140,T0000006895,85000,2019-07-31 21:52:48,AS339451,7140,S002,1
7141,T0000006896,100000,2019-07-31 23:35:25,OA027325,7141,S001,2
7142,T0000006897,85000,2019-07-31 23:39:35,TS624738,7142,S002,1
7143,T0000006898,85000,2019-07-31 23:41:38,AS834214,7143,S002,1

#### 데이터 결합 연습
1. transaction 데이터프레임과 csv 폴더 안에 item_master 파일을 로드하여 2개의 데이터프레임을 결합
2. 결합된 데이터에 csv 폴더에 customer_master 파일을 로드하여 데이터프레임을 결합
3. payment_date 컬럼의 데이터를 시계열데이터로 변환(to_datetime(시리즈))

In [108]:
# 파일 로드
item_master = pd.read_csv('../csv/item_master.csv')
customer_master = pd.read_csv('../csv/customer_master.csv')

In [109]:
item_master.head(1)

  item_id item_name  item_price
0    S001      PC-A       50000

In [110]:
customer_master.head(1)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0

In [111]:
item_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item_id     5 non-null      object
 1   item_name   5 non-null      object
 2   item_price  5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [112]:
customer_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4192 entries, 0 to 4191
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4192 non-null   object
 1   name         4192 non-null   object
 2   class        4192 non-null   object
 3   gender       4192 non-null   object
 4   start_date   4192 non-null   object
 5   end_date     1350 non-null   object
 6   campaign_id  4192 non-null   object
 7   is_deleted   4192 non-null   int64
dtypes: int64(1), object(7)
memory usage: 262.1+ KB

In [113]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  7144 non-null   object
 1   price           7144 non-null   int64
 2   payment_date    7144 non-null   object
 3   customer_id     7144 non-null   object
 4   detail_id       7144 non-null   int64
 5   item_id         7144 non-null   object
 6   quantity        7144 non-null   int64
dtypes: int64(3), object(4)
memory usage: 390.8+ KB

In [114]:
# transaction , item_master 조인 결합 -> 공통 컬럼은 item_id
df = transaction.merge(
    item_master,
    on = 'item_id',
    how  = 'inner',
    
)

In [115]:
df.info()
# item_master에서 결합된 컬럼 item_name, item_price의 결측치가 존재하지 않는다?
# 같은 집합 : item_id 기준으로 inner 결합 -> 인덱스도 유지 / 결측치도 존재x

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  7144 non-null   object
 1   price           7144 non-null   int64
 2   payment_date    7144 non-null   object
 3   customer_id     7144 non-null   object
 4   detail_id       7144 non-null   int64
 5   item_id         7144 non-null   object
 6   quantity        7144 non-null   int64
 7   item_name       7144 non-null   object
 8   item_price      7144 non-null   int64
dtypes: int64(4), object(5)
memory usage: 502.4+ KB

In [116]:
# df와 cutomer_master 조인 결합 -> 조건 customer_id
df = pd.merge(
    df, customer_master,
    on = 'customer_id',
    how = 'right'
)

In [117]:
# 시계열데이터 paymend_date를 컬럼을 타입ㅇ르 변경
# a문자를 시계열로 변경 (datetime.strptime() // to_datetime() )
pd.to_datetime(df['payment_date'])

0      2019-06-12 21:50:41
1      2019-04-22 22:52:53
2      2019-06-02 10:11:24
3      2019-07-15 20:57:48
4      2019-07-29 22:56:03
               ...
7704   2019-05-31 05:23:03
7705   2019-03-25 16:58:18
7706   2019-04-22 18:51:16
7707   2019-03-31 20:08:51
7708                   NaT
Name: payment_date, Length: 7709, dtype: datetime64[ns]

In [118]:
# datetime 라이브러리의 strptime()을 이용하여 데이터 타입 변환
from datetime import datetime

In [119]:
df['payment_date'][0]

'2019-06-12 21:50:41'

In [120]:
# datetime 안에 strptime() 함수는 pandas to_datetime()과는 다르게 시리즈 형태 변환 불가능
# datetime.strptime(df['payment_date'],'%Y-%m-%d %H:%M:%S')
# 시리즈 데이터에서 value들을 하나씩 뽑아서 함수에 넣는다 map()
df['payment_date'].map(
    # x에 대입이 되는 데이터는 문자
    lambda x : datetime.strptime(x, '%Y-%m-%d %H:%M:%S')

)

TypeError: strptime() argument 1 must be str, not float

In [ ]:
# 시리즈 데이터에서 문자열 함수를 사용하기 위해
    # 1.반복문 사용
    # 2. map() + lambda
    # 문자열 함수를 사용할수 있도록 pandas에서 제공한 Series.str ( StrinMethods )
# 시리즈에서는 시계열 함수를 사용할 수 있도록 문자열과 같이 datetimeMethods 변환이 존재
    # Series.dt --> 해당 데이터셋이 시계열로 시계열 함수

In [122]:
df['payment_date'] = pd.to_datetime(df['payment_date'])

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7709 entries, 0 to 7708
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6069 non-null   object
 1   price           6069 non-null   float64
 2   payment_date    6069 non-null   datetime64[ns]
 3   customer_id     7709 non-null   object
 4   detail_id       6069 non-null   float64
 5   item_id         6069 non-null   object
 6   quantity        6069 non-null   float64
 7   item_name       6069 non-null   object
 8   item_price      6069 non-null   float64
 9   name            7709 non-null   object
 10  class           7709 non-null   object
 11  gender          7709 non-null   object
 12  start_date      7709 non-null   object
 13  end_date        2493 non-null   object
 14  campaign_id     7709 non-null   object
 15  is_deleted      7709 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(10)
memory usage: 963.8+ KB

In [ ]:
# 요일별 판매가 된 제품들의 총 판매 개수의 합계가 어떻게 되는가?
# 요일이라는 새로운 변수를 생성 -> 시계열에서 요일만 따로 추출(strftime(%A|%a|%w))
df['요일'] = df['payment_date'].dt.strftime('%A')
# strftime(%w) -> 0(일),...

In [132]:
df['payment_date'].dt.weekday
# weekday -> 0(월),...

0       2.0
1       0.0
2       6.0
3       0.0
4       0.0
       ...
7704    4.0
7705    0.0
7706    0.0
7707    6.0
7708    NaN
Name: payment_date, Length: 7709, dtype: float64

In [133]:
df.head(1)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity,item_name,item_price,name,class,gender,start_date,end_date,campaign_id,is_deleted,요일
0,T0000005019,50000.0,2019-06-12 21:50:41,OA832399,5158.0,S001,1.0,PC-A,50000.0,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0,Wednesday

In [136]:
# 요일, item_id를 기준으로 그룹화 -> quantitiy의 합산
df[['요일','item_id','quantity']].groupby(['요일','item_id']).sum()

                   quantity
요일        item_id
Friday    S001        406.0
          S002        250.0
          S003        140.0
          S004        105.0
          S005        225.0
Monday    S001        363.0
          S002        201.0
          S003        132.0
          S004         97.0
          S005        207.0
Saturday  S001        367.0
          S002        182.0
          S003        141.0
          S004        102.0
          S005        231.0
Sunday    S001        390.0
          S002        236.0
          S003        121.0
          S004        121.0
          S005        210.0
Thursday  S001        334.0
          S002        206.0
          S003        128.0
          S004        103.0
          S005        227.0
Tuesday   S001        336.0
          S002        227.0
          S003        121.0
          S004        107.0
          S005        212.0
Wednesday S001        382.0
          S002        216.0
          S003         98.0
          S004        122.0
          S005        241.0